### PR TITLE
Task 442 - svm_options

### PR DESCRIPTION
**Pull request by ktalik**
#442 :+1: Both SVMLight and LibSVM support for command line arguments. Tests are included.

### CODE REVIEW

**Comment by igorsieradzki** [comment]
Compiling branch `task-442-svm-options` fails for me.

```
../inst/include/utils/utils.h:38:41: error: ‘class boost::shared_ptr<Logger>’ has no member named ‘log’
 #define LOG(logger, level, text) logger.log(level, text);
```

**Comment by ktalik** [comment]
TODO: `R` test

**Comment by ktalik** [comment]
Tests are ready. Reopening.

**Comment by kudkudak** [comment]
Changed assigned

**Comment by igorsieradzki** [comment]
Everything works, merging :+1:

**Pull request merged**
